config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :wishes
  resources :memories
  resources :photos
  get 'welcome/home'
  root 'welcome#home'
  get 'all', to: 'welcome#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memory.rb
class Memory < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  attachment :profile_image

end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/wish.rb
class Wish < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController

	def new
		@memory = Memory.new
	end

	def create
		@memory = Memory.new(memory_params)
		if @memory.save
			redirect_to root_path, notice: "Memory added! Thanks!"
		else
			render :new
		end
	end


private

	def memory_params
		params.require(:memory).permit(:body, :source)
	end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		if @photo.save
			redirect_to root_path, notice: "Photo added! Thanks!"
		else
			render :new
		end
	end


private

	def photo_params
		params.require(:photo).permit(:source, :caption, :photo_id, :photograph, :profile_image, :photograph_id)
	end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)
		if @picture.save
			redirect_to root_path, notice: "Picture added! Thanks!"
		else
			render :new
		end
	end


private

	def picture_params
		params.require(:picture).permit(:source, :caption, :picture_id, :photograph, :photograph_id)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def show
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
	def new
		@wish = Wish.new

	end

	def create
		@wish = Wish.new(wish_params)
		if @wish.save
			redirect_to root_path, notice: "Wish added! Thanks!"
		else
			render :new
		end
	end


private

	def wish_params
		params.require(:wish).permit(:body, :source)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeLoveHill</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1> <%= link_to "We Love Hill", root_path%></h1>
      <hr>
      <ul>
        <li><%= link_to "Photos", new_photo_path %></li>
        <li><%= link_to "Memories", new_memory_path %></li>
        <li><%= link_to "Wishes", new_wish_path %></li>
      </ul>
      <div class="container">

         <% if notice %>
            <div class="container">
               <div class="alert alert-info" role="alert">
                  <%= notice %>
                </div>
              </div>
          <% end %>

          <% if alert %>
          <div class="container">
              <div class="alert alert-danger" role="alert">
                  <%= alert %>
              </div>
          </div>
          <% end %>


         <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/memories/new.html.erb
<%= simple_form_for @memory, url: memories_path do |f| %>
  <%= f.input :body, label: "Your favorite memory of Hill...  " %>
  <%= f.input :source, label: "Your name" %>
  <%= f.button :submit%>
<% end %>

app/views/photos/new.html.erb
<%= simple_form_for @photo do |f| %>

    <%= f.label :profile_image %>
    <%= f.attachment_field :profile_image %>

  <%= f.input :caption %>
  <%= f.input :source, label: "Your name" %>
  <%= f.button :submit%>
<% end %>

app/views/pictures/new.html.erb
<%= simple_form_for @picture, url: pictures_path do |f| %>

    <%= f.label :photograph %>
    <%= f.attachment_field :photograph, as: :file %>

  <%= f.input :caption %>
  <%= f.input :source, label: "Your name" %>
  <%= f.button :submit%>
<% end %>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>

app/views/wishes/new.html.erb
<%= simple_form_for @wish, url: wishes_path do |f| %>
  <%= f.input :body, label: "Your wish for the birthday boy " %>
  <%= f.input :source, label: "Your name" %>
  <%= f.button :submit%>
<% end %>